import type { Catalog, ClosetConfig } from '@/types';
import { birdsEyeLegend, birdsEyeSvg } from '@/lib/birdseye';

// Presentational (no hooks). Renders the top-down floor plan + a legend.
export default function BirdsEyeView({
  catalog,
  config,
}: {
  catalog: Catalog;
  config: ClosetConfig;
}) {
  const svg = birdsEyeSvg(catalog, config);
  const legend = birdsEyeLegend(catalog);
  return (
    <div>
      <div
        className="overflow-x-auto rounded-lg border border-line bg-card p-3"
        // SVG generated by our own code from validated data.
        dangerouslySetInnerHTML={{ __html: svg }}
      />
      <div className="mt-2 flex flex-wrap gap-x-4 gap-y-1 text-xs text-muted">
        {legend.map((l) => (
          <span key={l.code}>
            <span className="font-semibold text-sand">{l.code}</span> = {l.label}
          </span>
        ))}
      </div>
    </div>
  );
}
