import type { Catalog, ClosetConfig } from '@/types';
import { formatCents, formatInches } from '@/lib/format';
import { closetSketchSvg } from '@/lib/sketch';
import { cartLayoutSvg, birdsEyeLegend } from '@/lib/birdseye';

// Presentational (no hooks) — used in the cart, checkout, and confirmation.
// Renders the 2D sketch plus the written, itemized selections.
//
// `layout="walls"` (passed only by the cart) swaps the front-elevation sketch
// for a per-wall top-down layout on L/U closets; everywhere else keeps the
// elevation sketch unchanged.
export default function ClosetSummary({
  catalog,
  config,
  totalCents,
  index,
  layout = 'sketch',
}: {
  catalog: Catalog;
  config: ClosetConfig;
  totalCents: number;
  index?: number;
  layout?: 'sketch' | 'walls';
}) {
  const material =
    catalog.materials.find((m) => m.id === config.materialId)?.label ??
    config.materialId;
  const colorLabel = (id: string) =>
    catalog.hardware.find((h) => h.id === id)?.label ?? id;
  const shape =
    catalog.shapes.find((s) => s.id === config.shape)?.label ?? config.shape;
  const hardwareStyle =
    catalog.hardwareStyles.find((s) => s.id === config.hardwareStyleId)?.label ??
    config.hardwareStyleId;
  const heightIn = config.heightUpgrade
    ? catalog.constraints.upgradedHeightIn
    : catalog.constraints.standardHeightIn;
  const totalWidthIn = config.sections.reduce((a, s) => a + s.widthIn, 0);
  const interiorLabel = (id: string) =>
    catalog.interiors.find((i) => i.id === id)?.label ?? id;
  // Everywhere shows the front-elevation ("face") sketch. In the cart, L/U
  // closets additionally show a per-wall top-down layout below it.
  const useWalls = layout === 'walls' && config.shape !== 'straight';
  const sketchSvg = closetSketchSvg(catalog, config);
  const wallsSvg = useWalls ? cartLayoutSvg(catalog, config) : null;
  const legend = useWalls ? birdsEyeLegend(catalog, config) : [];

  return (
    <div className="rounded-xl border border-line bg-card p-4">
      <div className="mb-3 flex items-center justify-between">
        <h3 className="font-semibold text-ink">
          {index != null ? `Closet ${index + 1}` : 'Closet'}
        </h3>
        <span className="font-semibold tabular-nums text-walnut">
          {formatCents(totalCents)}
        </span>
      </div>

      <div
        className="overflow-x-auto rounded-lg border border-cream bg-card p-2"
        // SVG is generated by our own code from validated data.
        dangerouslySetInnerHTML={{ __html: sketchSvg }}
      />
      {wallsSvg && (
        <div
          className="mt-2 overflow-x-auto rounded-lg border border-cream bg-card p-2"
          dangerouslySetInnerHTML={{ __html: wallsSvg }}
        />
      )}
      {legend.length > 0 && (
        <p className="mt-2 text-[11px] text-muted">
          {legend.map((l) => `${l.code} = ${l.label}`).join('   ')}
        </p>
      )}

      <p className="mt-3 text-xs font-semibold uppercase tracking-wide text-muted">
        Hardware &amp; Finish Details
      </p>
      <dl className="mt-1 grid grid-cols-2 gap-x-4 gap-y-1 text-sm">
        <dt className="text-muted">Shape</dt>
        <dd className="text-right text-ink">{shape}</dd>
        <dt className="text-muted">Material</dt>
        <dd className="text-right text-ink">{material}</dd>
        <dt className="text-muted">Hardware</dt>
        <dd className="text-right text-ink">
          {hardwareStyle} in {colorLabel(config.hardwareColorId)}
        </dd>
        <dt className="text-muted">Rod</dt>
        <dd className="text-right text-ink">{colorLabel(config.rodColorId)}</dd>
        <dt className="text-muted">Dimensions</dt>
        <dd className="text-right text-ink">
          {formatInches(totalWidthIn)} W × {formatInches(catalog.constraints.depthIn)} D ×{' '}
          {formatInches(heightIn)} H
        </dd>
      </dl>

      <ol className="mt-3 space-y-1 text-sm">
        {config.sections.map((s, i) => (
          <li key={s.id} className="flex justify-between">
            <span className="text-muted">
              Bay {i + 1}: {interiorLabel(s.interior)}
              {s.hasBack ? ' + back panel' : ''}
            </span>
            <span className="tabular-nums text-muted">{formatInches(s.widthIn)}</span>
          </li>
        ))}
      </ol>
    </div>
  );
}
