import type { Catalog, ClosetConfig } from '@/types';
import { formatCents, formatInches } from '@/lib/format';
import { closetSketchSvg } from '@/lib/sketch';

// Presentational (no hooks) — used in the cart, checkout, and confirmation.
// Renders the 2D sketch plus the written, itemized selections.
export default function ClosetSummary({
  catalog,
  config,
  totalCents,
  index,
}: {
  catalog: Catalog;
  config: ClosetConfig;
  totalCents: number;
  index?: number;
}) {
  const material =
    catalog.materials.find((m) => m.id === config.materialId)?.label ??
    config.materialId;
  const hardware =
    catalog.hardware.find((h) => h.id === config.hardwareId)?.label ??
    config.hardwareId;
  const heightIn = config.heightUpgrade
    ? catalog.constraints.upgradedHeightIn
    : catalog.constraints.standardHeightIn;
  const totalWidthIn = config.sections.reduce((a, s) => a + s.widthIn, 0);
  const interiorLabel = (id: string) =>
    catalog.interiors.find((i) => i.id === id)?.label ?? id;
  const svg = closetSketchSvg(catalog, config);

  return (
    <div className="rounded-xl border border-zinc-200 bg-white p-4">
      <div className="mb-3 flex items-center justify-between">
        <h3 className="font-semibold text-zinc-900">
          {index != null ? `Closet ${index + 1}` : 'Closet'}
        </h3>
        <span className="font-semibold tabular-nums text-walnut">
          {formatCents(totalCents)}
        </span>
      </div>

      <div
        className="overflow-x-auto rounded-lg border border-zinc-100 bg-white p-2"
        // SVG is generated by our own code from validated data.
        dangerouslySetInnerHTML={{ __html: svg }}
      />

      <dl className="mt-3 grid grid-cols-2 gap-x-4 gap-y-1 text-sm">
        <dt className="text-zinc-500">Material</dt>
        <dd className="text-right text-zinc-800">{material}</dd>
        <dt className="text-zinc-500">Hardware</dt>
        <dd className="text-right text-zinc-800">{hardware}</dd>
        <dt className="text-zinc-500">Dimensions</dt>
        <dd className="text-right text-zinc-800">
          {formatInches(totalWidthIn)} W × {formatInches(catalog.constraints.depthIn)} D ×{' '}
          {formatInches(heightIn)} H
        </dd>
      </dl>

      <ol className="mt-3 space-y-1 text-sm">
        {config.sections.map((s, i) => (
          <li key={s.id} className="flex justify-between">
            <span className="text-zinc-600">
              Bay {i + 1}: {interiorLabel(s.interior)}
              {s.hasBack ? ' + back panel' : ''}
            </span>
            <span className="tabular-nums text-zinc-500">{formatInches(s.widthIn)}</span>
          </li>
        ))}
      </ol>
    </div>
  );
}
